---
- hosts: frontend
  vars:
    http_port: 80
    max_clients: 200
  remote_user: vagrant
  become: true
  tasks:
  - name: Update HTTP to latest version.
    package:
      name: httpd
      state: present
    notify: restart server
  - name: Start httpd service
    service:
      name: httpd
      state: started
      enabled: yes
    notify: restart server
  - name: Copy Conf File
    copy: 
      src: /home/ansible/file1.txt
      dest: /tmp/file4.txt
    notify: restart server
  handlers:
  - name: restart server
    command: 'shutdown -r -t sec 20'